### PR TITLE
Fix: Connected shape duplication & place on fold to backend

### LINKED ISSUE #41: UI Pattern Duplication
Pattern Piece Duplication - mark in UI which pieces need to be duplicated, serialize info and send new svg to backend
Due Jan 15

### LINKED ISSUE #42: UI mark centre folds
Cut-on-fold pieces - mark in UI centre fold lines
Due Jan 21

### PR DESCRIPTION
**Pull request by Joshua-Pow**
## Description

Connected the backend and frontend to allow for:

- Shape duplication
- Shape place on fold
  - place on fold location
 
 Added input for fabric length

Fixes #41 
Implements #42

## How it was implemented

Changed backend to take in an array of svgs objects instead of just one:
```
{
    "svg": [
        {
            "id": 1,
            "quantity": 1,
            "canRotate": false,
            "placeOnFold": false,
            "foldLocation"?: "top",
            "svgString": "<path id='a' ... />"
        }
    ]
}
```

Added input textbox for fabric length as well as radio buttons to select place on fold location of a shape

## How it was tested

Manually

## Screenshots or video

https://github.com/Joshua-Pow/Placement/assets/51868988/aa6165e3-cee3-4f67-a4c9-9bec3208b7bd

### CODE REVIEW

File: src/components/FileUpload.tsx [hunk 1]
```diff
@@ -55,10 +75,14 @@ const FileUpload = () => {
     setLoading(true);
     const formData = new FormData();
     formData.append('file', pdf);
+    if (fabricLength !== undefined) {
```
Comment (li-grace) [inline src/components/FileUpload.tsx]: Is there a way to keep this fabric length stored in the frontend for displaying the iterations?

Comment (Joshua-Pow) [reply src/components/FileUpload.tsx]: Yep, but what is the purpose of that?

File: src/components/FileUpload.tsx [hunk 2]
```diff
@@ -8,19 +8,35 @@ import axios from 'axios';
...
 const EditSVGPage = dynamic(() => import('./EditSVGPage'), { ssr: false });
 
+type FabricUnit = 'in' | 'cm';
+
 const FileUpload = () => {
   const { toast } = useToast();
   const inputRef = React.useRef<HTMLInputElement>(null);
   const [filePath, setFilePath] = useState<string | null>(null);
   const [pdf, setPdf] = useState<string | Blob>('');
+  const [fabricLength, setFabricLength] = useState<number | undefined>(
```
Comment (li-grace) [inline src/components/FileUpload.tsx]: this should be fabric width actually

File: src/components/FileUpload.tsx (hunk 1 above)
Comment (li-grace) [reply src/components/FileUpload.tsx]: the display of the layout for each iteration should look relatively similar if not the same.
the length of the fabric may vary but the width is fixed. Since we're displaying things "sideways" (i.e. the length goes left-right on the screen, the width goes up-down)

File: src/components/FileUpload.tsx (hunk 2 above)
Comment (li-grace) [reply src/components/FileUpload.tsx]: yeah rename this var and then address any todos (not sure if you left them or someone else) and this PR should begood to go

File: src/components/FileUpload.tsx (hunk 1 above)
Comment (Joshua-Pow) [reply src/components/FileUpload.tsx]: Ok, when rendering the iterations this variable will still be in scope so we can use it, but I think the issue is in the backend when generating the shape orientation.

[See here](https://github.com/Joshua-Pow/Placement/blob/c375044f95ca5b9f538dfd749c5970069cddaca1/api/index.py#L169C9-L181C10)

File: src/components/FileUpload.tsx (hunk 2 above)
Comment (Joshua-Pow) [reply src/components/FileUpload.tsx]: Fixed

**Review by jongjin-j — APPROVED** [review]
Looks good to me
